config/routes.rb
Rails.application.routes.draw do
  get "producttype/show"
  resources :genders
  get "producttype/show/product_type_id=:id" => "producttype#show", :as => :producttype
  get "chart/index"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index", as: "home_index"
  resources :store
  resources :home
  resources :orders
  resources :line_items
  resources :carts
  resources :types

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    get :who_bought, on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
    if params[:query].present?
      @products = Product.search(params[:query]).paginate(page: params[:page], per_page: 15).order(created_at: :desc)
    else
      @products = Product.all.paginate(page: params[:page], per_page: 15).order(created_at: :desc)
    end
    if current_user
      if current_user.admin == true
        redirect_to rails_admin_path
      end
    end
  end
end

app/views/home/index.html.erb
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<head>
	<title>Free Adidas Website Template | Home :: w3layouts</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="/assets/style.css" rel="stylesheet" type="text/css" media="all" />
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="/assets/jquery.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$(".dropdown img.flag").addClass("flagvisibility");

			$(".dropdown dt a").click(function () {
				$(".dropdown dd ul").toggle();
			});

			$(".dropdown dd ul li a").click(function () {
				var text = $(this).html();
				$(".dropdown dt a span").html(text);
				$(".dropdown dd ul").hide();
				$("#result").html("Selected value is: " + getSelectedValue("sample"));
			});

			function getSelectedValue(id) {
				return $("#" + id).find("dt a span.value").html();
			}

			$(document).bind('click', function (e) {
				var $clicked = $(e.target);
				if (!$clicked.parents().hasClass("dropdown"))
					$(".dropdown dd ul").hide();
			});


			$("#flagSwitcher").click(function () {
				$(".dropdown img.flag").toggleClass("flagvisibility");
			});
		});
	</script>
	<!-- start menu -->
	<link href="/assets/megamenu.css" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="/assets/megamenu.js"></script>
	<script>
		$(document).ready(function () {
			$(".megamenu").megamenu();
		});
	</script>
	<!-- end menu -->
	<!-- top scrolling -->
	<script type="text/javascript" src="/assets/move-top.js"></script>
	<script type="text/javascript" src="/assets/easing.js"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1200);
			});
		});
	</script>
</head>

<body>

	<div class="index-banner">
		<div class="wmuSlider example1" style="height: 560px;">
			<div class="wmuSliderWrapper">
				<article style="position: relative; width: 100%; opacity: 1;">
					<div class="banner-wrap">
						<div class="slider-left">
							<img src="/assets/banner1.jpg" alt="" />
						</div>
						<div class="slider-right">
							<h1>Classic</h1>
							<h2>White</h2>
							<p>Lorem ipsum dolor sit amet</p>
							<div class="btn">
								<%= link_to "Shop Now", store_index_path %>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</article>
				<article style="position: absolute; width: 100%; opacity: 0;">
					<div class="banner-wrap">
						<div class="slider-left">
							<img src="/assets/banner2.jpg" alt="" />
						</div>
						<div class="slider-right">
							<h1>Classic</h1>
							<h2>White</h2>
							<p>Lorem ipsum dolor sit amet</p>
							<div class="btn">
								<%= link_to "Shop Now", store_index_path %>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</article>
				<article style="position: absolute; width: 100%; opacity: 0;">
					<div class="banner-wrap">
						<div class="slider-left">
							<img src="/assets/banner1.jpg" alt="" />
						</div>
						<div class="slider-right">
							<h1>Classic</h1>
							<h2>White</h2>
							<p>Lorem ipsum dolor sit amet</p>
							<div class="btn">
								<%= link_to "Shop Now", store_index_path %>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</article>
				<article style="position: absolute; width: 100%; opacity: 0;">
					<div class="banner-wrap">
						<div class="slider-left">
							<img src="/assets/banner2.jpg" alt="" />
						</div>
						<div class="slider-right">
							<h1>Classic</h1>
							<h2>White</h2>
							<p>Lorem ipsum dolor sit amet</p>
							<div class="btn">
								<%= link_to "Shop Now", store_index_path %>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</article>
				<article style="position: absolute; width: 100%; opacity: 0;">
					<div class="banner-wrap">
						<div class="slider-left">
							<img src="/assets/banner1.jpg" alt="" />
						</div>
						<div class="slider-right">
							<h1>Classic</h1>
							<h2>White</h2>
							<p>Lorem ipsum dolor sit amet</p>
							<div class="btn">
								<%= link_to "Shop Now", store_index_path %>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</article>
			</div>
			<a class="wmuSliderPrev">Previous</a>
			<a class="wmuSliderNext">Next</a>
			<ul class="wmuSliderPagination">
				<li>
					<a href="#" class="">0</a>
				</li>
				<li>
					<a href="#" class="">1</a>
				</li>
				<li>
					<a href="#" class="wmuActive">2</a>
				</li>
				<li>
					<a href="#">3</a>
				</li>
				<li>
					<a href="#">4</a>
				</li>
			</ul>
		
		</div>
		<script src="/assets/jquery.wmuSlider.js"></script>
		<script type="text/javascript" src="/assets/modernizr.custom.min.js"></script>
		<script>
			$('.example1').wmuSlider();
		</script>
	</div>
	<div class="main">
		<div class="wrap">
			<% @products.each do |product| %>
				<div class="box1">

					<div class="col_1_of_single1 span_1_of_single1">

							<div class="view1 view-fifth1">
								<div class="top_box">
									<h3 class="m_1">
										<%= product.title %>
									</h3>
									<p class="m_2"><%= product.description %></p>

									<div class="grid_img">
										<%= image_tag product.image.url(:medium), :size =>"250x175"%>
											<div class="mask1">
												<%= link_to 'Details Product', product_path(product), :class => "info" %>
											</div>
									</div>
									<div class="price">
										<%= number_to_currency(product.price, precision: 0, unit: "VND", separator: ",", format: "%n %u") %>
									</div>
								</div>
							</div>
							
							<ul class="list2">
								<li>
									<img src="/assets/plus.png" alt="" />
									<ul class="icon1 sub-icon1 profile_img">
										<li>
											<a>
												<%= button_to 'Add To Cart', line_items_path(product_id: product), remote: true, :class=>"active-icon" %>
											</a>
											
										</li>
									</ul>
								</li>
							</ul>
							<div class="clear"></div>
						</a>
					</div>
					<% end %>
						</a>
						</a>
						</a>
						</a>
						</a>

						<div class="clear"></div>
						<div class="clear"></div>
						</a>
				</div>

		</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>

</body>

</html>