config/routes.rb
Rails.application.routes.draw do
  get "producttype/show"
  resources :genders
  get "producttype/show/product_type_id=:id" => "producttype#show", :as => :producttype
  get "chart/index"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index", as: "home_index"
  resources :store
  resources :home
  resources :orders
  resources :line_items
  resources :carts
  resources :types

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    get :who_bought, on: :member
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  $a

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
    $a = line_items.to_a.sum { |item| item.total_price }
  end

  def self.total
    return $a
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to request.referrer }  #empty cart xong vẫn ở trang đang đứng
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: "Invalid cart"
  end
end

app/views/carts/_cart.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<% unless cart.line_items.empty? %>
<h2>Your Cart</h2>
<table class="table table-hover">
        <thead>
                <tr>                               
                    <th style="font-weight: bold">Qt</th>
                    <th style="font-weight: bold">Product</th>
                    <th style="font-weight: bold">Price</th>
                </tr>
            </thead>
    <%= render(cart.line_items) %>
        <tr class="total_line">
            <td colspan="2">Total</td>
            <td class="total_cell">
                <%= number_to_currency(cart.total_price, precision: 0, unit: "VND", separator: ",", format: "%n %u") %>
            </td>
        </tr>
    </table>
<%= button_to "Checkout", new_order_path, method: :get, :class => "btn-info" %>
<%= button_to 'Empty cart', cart, method: :delete,
data: { confirm: 'Really nigga?' }, :class => "btn-danger" %>
<% end %>
<div class="clear"></div>

app/views/carts/index.html.erb
<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Really nigga' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<%= render @cart %>